### ISSUE TITLE
Initial tasks.

### ISSUE THREAD

**Issue by sumith1896** [rohan-3496/ITSP-2015#2]
Rohan: Proposal update+branch and commit, never commit to master
Rupanshu and Yogesh: Fork and send PRs

**Comment by sumith1896** [comment]
@rohan-3496 @rupanshuganvir Let's discuss here.

**Comment by rohan-3496** [comment]
BC yeh kha se aya ?? .. but still its nyc

**Comment by rohan-3496** [comment]
OK .. some doubts first..

i) Do we have a sample code?
ii)In which language are we coding the project?

**Comment by sumith1896** [comment]
Okay ground rules: this is public, people who follow you can see your comments, so language.
Plus to the point discussion. :+1:

**Comment by Yogeshkumar4** [comment]
Strategy ???

**Comment by sumith1896** [comment]
Python will do, else we'll have a hard time.
We have to find some sample code.

**Comment by Yogeshkumar4** [comment]
okkk .. python is good ..

**Comment by rohan-3496** [comment]
Python?? Whatever happened to C++?

**Comment by sumith1896** [comment]
But now we are too late for c++, we wont finish in time.

**Comment by rohan-3496** [comment]
To pehle yeh bta .. do we have any IDE for python like code::Blocks for C++?

**Comment by sumith1896** [comment]
Guys come [here](https://gitter.im/rohan-3496/ITSP-2015?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by sumith1896** [comment]
The repo updated. Closing this.
